common:
  app: ashur
  shortname: ashur
  team: ror
  ingress:
    enabled: false
  service:
    externalPort: 80
    internalPort: 8080
  hpa:
    spec:
      minReplicas: 1
      maxReplicas: 1
  container:
    image: <+artifacts.primary.image>
    forceReplicas: 1
    cpu: 5
    memory: 8000
    memoryLimit: 9000
    probes:
      liveness:
        path: /actuator/health/liveness
      readiness:
        path: /actuator/health/readiness
    prometheus:
      enabled: true
      path: /actuator/prometheus
    volumeMounts:
      - mountPath: /etc/application-config
        name: application-config
        readOnly: true
    volumes:
      - configMap:
          defaultMode: 420
          name: ashur-application
        name: application-config
  configmap:
    data:
      JDK_JAVA_OPTIONS: -server -Xmx7000m -Xss512k -XX:MaxGCPauseMillis=1000
        -Dspring.config.location=/etc/application-config/application.properties
        -Dfile.encoding=UTF-8
      TZ: Europe/Oslo
    enabled: true
    toEnv: true
